server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: TaskBoard.DropStack.Boot

  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://${MONGO_ROOT_USER:root}:${MONGO_ROOT_PASSWORD:password}@taskboard-dropstack-mongo:27017/${MONGO_DB_NAME:taskboard_dropstack}?authSource=admin}

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_SERVER_URL:http://localhost:8081}/realms/TodoRealm
          jwk-set-uri: ${KEYCLOAK_SERVER_URL:http://localhost:8081}/realms/TodoRealm/protocol/openid-connect/certs

  servlet:
    multipart:
      max-file-size: ${SPRING_SERVLET_MULTIPART_MAX_FILE_SIZE:50MB}
      max-request-size: ${SPRING_SERVLET_MULTIPART_MAX_REQUEST_SIZE:100MB}
      enabled: true


minio:
  endpoint: ${MINIO_ENDPOINT:http://taskboard-dropstack-minio:9000}
  access-key: ${MINIO_ACCESS_KEY:minioadmin}
  secret-key: ${MINIO_SECRET_KEY:change_me_minio_strong}
  bucket: ${MINIO_BUCKET:taskboard-dropstack-docs}
  region: ${MINIO_REGION:eu-south-1}
  secure: ${MINIO_SECURE:false}
